### PR TITLE
React 18 `<StrictMode>` tweaks and bug fixes

### PR DESCRIPTION
**Pull request by clauderic**
This PR fixes some issues with @dnd-kit when used with React 18 `<StrictMode>`

### CODE REVIEW

**Comment by JakubKontra** [comment]
Any progress here?

**Comment by Skaidon** [comment]
Will this cover adding support to other packages like `@dnd-kit/accessibility@3.0.1`?

**Comment by rsdrsd** [comment]
It would be nice if this is going to be merged. It solves a lot of problems for react 18 installs.

**Comment by vldnovikov** [comment]
Any updates?

**Comment by vldnovikov** [comment]
Look's like no one cares about it, I probably need to switch to `react-beautiful-dnd`

**Comment by JakubKontra** [comment]
> Look's like no one cares about it, I probably need to switch to `react-beautiful-dnd`

same here.

**Comment by clauderic** [comment]
I'm planning to work on this over the holiday break. Please keep in mind that this is an open source project, and if you want things to move faster, feel free to open a PR or sponsor the project.

**Comment by ivanjeremic** [comment]
> Look's like no one cares about it, I probably need to switch to `react-beautiful-dnd`

there is also [https://react-spectrum.adobe.com/react-aria/dnd.html](https://react-spectrum.adobe.com/react-aria/dnd.html) maybe it has what you need.

**Comment by Eduard-Hasa** [comment]
> I'm planning to work on this over the holiday break. Please keep in mind that this is an open source project, and if you want things to move faster, feel free to open a PR or sponsor the project.

I have no problem becoming a sponsor if it can help toy make the sortable tree example work properly. https://github.com/clauderic/dnd-kit/issues/860   

Does this PR fix that issue described?

**Comment by vldnovikov** [comment]
@Eduard-Hasa Yes, it's the same bug

**Comment by Eduard-Hasa** [comment]
> @Eduard-Hasa Yes, it's the same bug

If it's the same bug then does that mean strict mode in react 18 is causing my issue? My issue occurs in the dnd-kit storybook tree example as well. O tried turning off strict mode on my project and still seeing the issue.

I have literally looked at every other library and this one is amazing. Not sure how this project is dying without any support.

**Comment by Eduard-Hasa** [comment]
I can confirm that the code in this pull request fixes the issues in https://github.com/clauderic/dnd-kit/issues/860
@clauderic I can say that after weeks of desperation to find a good drag and drop library and desperately trying to find a better one due to this issue... I can preach that nothing comes remotely close to dnd kit. Your work on this library is nothing short of amazing and it really sucks to not see it not as actively worked on anymore. 

Coming from a user perspective I would so much rather pay a monthly fee for a actively maintained library then see this go. Please try to start some discussions with the community to see what we as users can do to help you maintain it and keep the library alive.

**Comment by vldnovikov** [comment]
@clauderic any updates?

**Pull request merged**
