### PR TITLE
Improve `useDraggable` usage without `<DragOverlay>`

### PR DESCRIPTION
**Pull request by clauderic**
Fixes https://github.com/clauderic/dnd-kit/issues/348, https://github.com/clauderic/dnd-kit/issues/659

This PR fixes a number of issues with `useDraggable` when used without `<DragOverlay>`.

## Resize observer for `activeNodeRect` and `containerNodeRect`

The `activeNodeRect` and `containerNodeRect` are now observed in case they resize while dragging.

### Before

https://user-images.githubusercontent.com/1416436/158506966-d6d27cb5-cf2e-4fa6-8c41-04e4223614d2.mov

### After

https://user-images.githubusercontent.com/1416436/158507217-20203562-3410-4ef9-8d58-8b6cc9284f5f.mov

### Before

https://user-images.githubusercontent.com/1416436/158507027-7b69a2cc-9a5b-4f8c-9d6f-bee76d046b86.mov

### After

https://user-images.githubusercontent.com/1416436/158507114-842cc32b-1506-4093-b0c3-4b76c77e5de3.mov

### CODE REVIEW

**Comment by nickrobillard** [comment]
Just wanted to mention - I have been using this to overcome the "scrolling" issue in your first video. It is working as expected so far. Thank you for this!

**Comment by GradySain** [comment]
@nickrobillard can u share a snippet of how you are using this? I'm new to dnd-kit and am experiencing the scrolling issue...

**Comment by gabrielclaudino** [comment]
@GradySain AFAIK you don't need to change they way you are using it. Just update your project to the @next version. You can [checkout all the releases listed here](https://www.npmjs.com/package/@dnd-kit/core/v/6.0.0-next-2022420172442).

**Comment by GradySain** [comment]
sounds great thanks!

**Pull request merged**
