### PR TITLE
Add @storybook/addon-storysource

### PR DESCRIPTION
**Pull request by akhmadullin**
solves https://github.com/clauderic/dnd-kit/issues/291

This PR adds @storybook/addon-storysource to the dnd-kit project. This addon provides each story page with its source code.

### CODE REVIEW

**Comment by akhmadullin** [comment]
I'm not sure about necessity of `changeset` for this PR, because all dnd-kit packages stayed the same.
I just changed some files in root repo.

Should I add ``changeset`` in this case?

If yes, what dnd-kit packages to select via ``yarn .changeset``?

**Comment by clauderic** [comment]
Hey @akhmadullin, thanks for your contribution. I'm not sure if merging this PR would really address the issue described in #291.

In practice, most stories are authored for code shareability and are hard to read. Having this addon enabled wouldn't really solve that.

The code it would show would look something like this, which isn't super helpful in my opinion:

```tsx
export const BasicSetup = () => <Sortable {...props} />;

export const WithoutDragOverlay = () => (
  <Sortable {...props} useDragOverlay={false} itemCount={5} />
);

export const DragHandle = () => <Sortable {...props} handle />;
```

**Comment by akhmadullin** [comment]
@clauderic, ok

I also expected, that this addon would add the source code of whole ``.story.tsx`` file - previously addon had worked in this way, but now it shows only the source code of selected story.

[Addon docs](https://www.npmjs.com/package/@storybook/addon-storysource) says, that the addon behavior changed in 6.0.0 version, and it has options to enable full source code (of whole file) - I tried to use it, but it does not work.

I will try to fix it, but I'm not sure, that my attempt will be successful.

**Comment by ddublon** [comment]
can you make it more easy to use please?
why it is so compilated to see the code?
i want to copy and past the example and then modify it to my needs

**Pull request closed without merging**
