### PR TITLE
Refactor measuring and collision detection

### PR DESCRIPTION
**Pull request by clauderic**
This PR reduces the number of concepts related to measuring from `ViewRect`, `LayoutRect` to just a single concept of `ClientRect`.

Previously, all collision detection algorithms were relative to the top and left points of the document. While this approach worked in most situations, it broke down in a number of different use-cases: #43, #73, #98, #263, #325, #483, etc.

This new approach changes the frame of comparison to be relative to the viewport. This is a major breaking change, and will need to be released under a new major version bump.

This PR also introduces a changed approach to measuring the `ClientRect` of draggable and droppable elements. Previously, the `offsetTop` and `offsetLeft` properties of an element and all of its positioned ancestors were used to compute the rect that was used for collision detection. This approach had a number of limitations however, and failed when the draggable or droppable elements were positioned within transformed elements (since `offsetTop` and `offsetLeft` properties do not take into account transforms): #464 

By default, @dnd-kit now ignores only the `transforms` applied to the draggable / droppable node itself, but considers all the transforms applied to its ancestors. This should provide the right balance of flexibility for most consumers. 

Transforms applied to the droppable and draggable nodes are ignored by default, because the recommended approach for moving items on the screen is to use the `transform` property, which can interfere with the calculation of collisions. 

Consumers can choose an alternate approach that does consider transforms for specific use-cases if needed by configuring the `measuring` prop of `<DndContext>`. Refer to the `<Switch>` example.

### CODE REVIEW

**Comment by baptisteArno** [comment]
I'm eagerly waiting for this update 💪

Let me know if I can help in any way @clauderic

**Comment by CodexpathCommunity** [comment]
how can I use this solution in my app when I'm having container detection with long scrolling container

**Comment by prallhsu** [comment]
> This PR reduces the number of concepts related to measuring from `ViewRect`, `LayoutRect` to just a single concept of `ClientRect`.
> 
> Previously, all collision detection algorithms were relative to the top and left points of the document. While this approach worked in most situations, it broke down in a number of different use-cases: #43, #73, #98, #263, #325, #483, etc.
> 
> This new approach changes the frame of comparison to be relative to the viewport. This is a major breaking change, and will need to be released under a new major version bump.
> 
> This PR also introduces a changed approach to measuring the `ClientRect` of draggable and droppable elements. Previously, the `offsetTop` and `offsetLeft` properties of an element and all of its positioned ancestors were used to compute the rect that was used for collision detection. This approach had a number of limitations however, and failed when the draggable or droppable elements were positioned within transformed elements (since `offsetTop` and `offsetLeft` properties do not take into account transforms): #464
> 
> By default, @dnd-kit now ignores only the `transforms` applied to the draggable / droppable node itself, but considers all the transforms applied to its ancestors. This should provide the right balance of flexibility for most consumers.
> 
> Transforms applied to the droppable and draggable nodes are ignored by default, because the recommended approach for moving items on the screen is to use the `transform` property, which can interfere with the calculation of collisions.
> 
> Consumers can choose an alternate approach that does consider transforms for specific use-cases if needed by configuring the `measuring` prop of `<DndContext>`. Refer to the `<Switch>` example.

How can i config DndContext to apply  transforms property on my droppable node itself，i'm confusing with the `<Switch>` example，and i had tried to config measuring property，but it's not working. @clauderic 
`measuring={{
        droppable: {
          measure: (element: HTMLElement) => element.getBoundingClientRect(),
        },
      }}`

**Comment by prallhsu** [comment]
Sry，it works fine，but my droppable area has a transform animation when i begin to drag. So when i add `frequency` props in measuring config， everything works fine!

**Pull request merged**
