### PR TITLE
Add activatorEvent to DragStartEvent

### LINKED ISSUE #1139: Expose activatorEvent for onDragStart
Is there a technical reason for not exposing `activatorEvent` in `DragStartEvent`?

My use case is to render `DragOverlay`/dragged item differently during a keyboard activated drag event.

### PR DESCRIPTION
**Pull request by anilanar**
Fixes #1139.

### CODE REVIEW

**Comment by nicostombros** [comment]
@clauderic Is this something that can be merged in?

**Comment by Annoiiyed** [comment]
@clauderic Sorry to bump this again, but, I think due to #832 and this not being merged, right now it seems next to impossible to get information on the location of a drag start. Would it be possible to merge this? :)

**Comment by stnwk** [comment]
Pretty please?

**Comment by joacoespinosa** [comment]
🙏

**Comment by hqw567** [comment]
Can we merge codes? I need to use rect in `onDragMove` . 
To achieve some specific needs, such as similar to mobile phone desktop icon drag, icon overlap to create icon folders.
It's been a problem for two years.
@clauderic

**Comment by CreativeDive** [comment]
You can access the onDragStart event data using this way. Add an custom `onMouseDown` event to the handle and don't forget to pass the `listeners.onMouseDown(e);` too:

```js
const ResizeHandle = ({ id, axis, side, onResizeStart, onResize }) => {
    const { attributes, listeners, setNodeRef, transform } = useDraggable({
        id,
    });

    useEffect(() => {
        if (transform) {
            onResize(transform, id);
        }
    }, [transform, onResize, id]);

    const handleMouseDown = (e) => {
        onResizeStart(e, id);
        if (listeners.onMouseDown) {
            listeners.onMouseDown(e);
        }
    };

    return (
        <div
            ref={setNodeRef}
            {...listeners}
            {...attributes}
            onMouseDown={handleMouseDown}
            className={`resize-handle resize-handle-${axis} resize-handle-${side}`}>
            <div className='wphave-handle' />
        </div>
    );
};
```

**Comment by Ethorsen** [comment]
Also need the activatorEvent in dragStart.   Will implement a sketchy work-around for now

**Review by clauderic — APPROVED** [review]

**Pull request merged**
