### PR TITLE
Move @dnd-kit/core as a `peerDependencies` for other @dnd-kit packages that depend on it

### PR DESCRIPTION
**Pull request by akhmadullin**
solves #293

### CODE REVIEW

**Comment by clauderic** [comment]
I believe only `@dnd-kit/core` should be listed as a peerDependency of the other packages, otherwise consumers will need to manually specify packages such as `@dnd-kit/accessibility` in their dependencies, which isn't something they should have to do.

**Comment by akhmadullin** [comment]
Ok

So, there will also be no problem with `@dnd-kit/utilities`, if it stays mentioned as dependency?

Now `@dnd-kit/utilities` is used as dependency in `@dnd-kit/core` and also it mentioned as dependency in `@dnd-kit/modifiers` and `@dnd-kit/sortable`, which, in turn, use `@dnd-kit/core` as dependency.

How do you think, is it possible, that someone can face with problem of having several different versions of  `@dnd-kit/utilities` in his project, like we had 2 different versions of `@dnd-kit/core`?

If it is not possible, I will list only `@dnd-kit/core` as peerDependency.

Is it ok, if I just edit my previous commits and force-push them or I should push new commits, based on my previous ones, and they will be merged/squashed soon all together?

**Comment by clauderic** [comment]
It could potentially happen for consumers to end up with two versions of `@dnd-kit/utilities`, but it's less problematic than having two versions of `@dnd-kit/core`. Having two versions of `@dnd-kit/core` causes issues with React context which causes the issues of `@dnd-kit/sortable` not working at all.

`@dnd-kit/utilities` is a package that does not change often, and shouldn't have breaking changes that would cause major issues even if two versions were installed. Installing `@dnd-kit/utilities` should be optional for consumers, which is why I'm reluctant for it to be added as a peer dependency.

**Comment by akhmadullin** [comment]
Ok, I got it

**Comment by akhmadullin** [comment]
Is it ok, if I just force-push edited commits instead of current commits?

**Comment by clauderic** [comment]
Yes that's fine, just make sure you update the `.changeset` to reflect the new changes

**Comment by akhmadullin** [comment]
@clauderic, I updated commits.

It seems, that they are ok now.

Should I do anything else to get this PR approved?

**Pull request merged**
